/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiConciergeImageRouteImport } from './routes/api/concierge-image'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as CollectionSlugIndexRouteImport } from './routes/collection.$slug.index'
import { Route as CollectionSlugVariantRouteImport } from './routes/collection.$slug.$variant'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SubscribeReturnRouteImport } from './routes/subscribe.return'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiConciergeImageRoute = ApiConciergeImageRouteImport.update({
  id: '/api/concierge-image',
  path: '/api/concierge-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CollectionSlugIndexRoute = CollectionSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionSlugRoute,
} as any)
const CollectionSlugVariantRoute = CollectionSlugVariantRouteImport.update({
  id: '/$variant',
  path: '/$variant',
  getParentRoute: () => CollectionSlugRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeReturnRoute = SubscribeReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => SubscribeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/subscribe/return': typeof SubscribeReturnRoute
  '/atelier': typeof AtelierRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collection': typeof CollectionRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/system': typeof SystemRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/concierge-image': typeof ApiConciergeImageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collection/$slug': typeof CollectionSlugRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection/': typeof CollectionIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/collection/$slug/$variant': typeof CollectionSlugVariantRoute
  '/collection/$slug/': typeof CollectionSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/subscribe/return': typeof SubscribeReturnRoute
  '/atelier': typeof AtelierRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalIndexRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/system': typeof SystemRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/concierge-image': typeof ApiConciergeImageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection': typeof CollectionIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/collection/$slug/$variant': typeof CollectionSlugVariantRoute
  '/collection/$slug': typeof CollectionSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscribe': typeof SubscribeRouteWithChildren
  '/subscribe/return': typeof SubscribeReturnRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/atelier': typeof AtelierRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collection': typeof CollectionRouteWithChildren
  '/concierge': typeof ConciergeRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/membership': typeof MembershipRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscription': typeof SubscriptionRoute
  '/system': typeof SystemRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/concierge-image': typeof ApiConciergeImageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collection/$slug': typeof CollectionSlugRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection/': typeof CollectionIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/collection/$slug/$variant': typeof CollectionSlugVariantRoute
  '/collection/$slug/': typeof CollectionSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscribe'
    | '/subscribe/return'
    | '/atelier'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/concierge'
    | '/contact'
    | '/forgot-password'
    | '/inventory'
    | '/journal'
    | '/login'
    | '/manifesto'
    | '/membership'
    | '/reset-password'
    | '/subscription'
    | '/system'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/api/concierge'
    | '/api/concierge-image'
    | '/checkout/return'
    | '/collection/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collection/'
    | '/journal/'
    | '/api/public/paystack-webhook'
    | '/collection/$slug/$variant'
    | '/collection/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscribe'
    | '/subscribe/return'
    | '/atelier'
    | '/cart'
    | '/checkout'
    | '/concierge'
    | '/contact'
    | '/forgot-password'
    | '/inventory'
    | '/journal'
    | '/login'
    | '/manifesto'
    | '/membership'
    | '/reset-password'
    | '/subscription'
    | '/system'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/api/concierge'
    | '/api/concierge-image'
    | '/checkout/return'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collection'
    | '/api/public/paystack-webhook'
    | '/collection/$slug/$variant'
    | '/collection/$slug'
  id:
    | '__root__'
    | '/'
    | '/subscribe'
    | '/subscribe/return'
    | '/_authenticated'
    | '/atelier'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/concierge'
    | '/contact'
    | '/forgot-password'
    | '/inventory'
    | '/journal'
    | '/login'
    | '/manifesto'
    | '/membership'
    | '/reset-password'
    | '/subscription'
    | '/system'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/concierge'
    | '/api/concierge-image'
    | '/checkout/return'
    | '/collection/$slug'
    | '/journal/$slug'
    | '/product/$slug'
    | '/collection/'
    | '/journal/'
    | '/api/public/paystack-webhook'
    | '/collection/$slug/$variant'
    | '/collection/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscribeRoute: typeof SubscribeRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtelierRoute: typeof AtelierRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CollectionRoute: typeof CollectionRouteWithChildren
  ConciergeRoute: typeof ConciergeRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRoute
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManifestoRoute: typeof ManifestoRoute
  MembershipRoute: typeof MembershipRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SystemRoute: typeof SystemRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  ApiConciergeImageRoute: typeof ApiConciergeImageRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof CollectionRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/concierge-image': {
      id: '/api/concierge-image'
      path: '/api/concierge-image'
      fullPath: '/api/concierge-image'
      preLoaderRoute: typeof ApiConciergeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/collection/$slug/': {
      id: '/collection/$slug/'
      path: '/'
      fullPath: '/collection/$slug/'
      preLoaderRoute: typeof CollectionSlugIndexRouteImport
      parentRoute: typeof CollectionSlugRoute
    }
    '/collection/$slug/$variant': {
      id: '/collection/$slug/$variant'
      path: '/$variant'
      fullPath: '/collection/$slug/$variant'
      preLoaderRoute: typeof CollectionSlugVariantRouteImport
      parentRoute: typeof CollectionSlugRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/return': {
      id: '/subscribe/return'
      path: '/return'
      fullPath: '/subscribe/return'
      preLoaderRoute: typeof SubscribeReturnRouteImport
      parentRoute: typeof SubscribeRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SubscribeRouteChildren {
  SubscribeReturnRoute: typeof SubscribeReturnRoute
}
const SubscribeRouteChildren: SubscribeRouteChildren = {
  SubscribeReturnRoute: SubscribeReturnRoute,
}
const SubscribeRouteWithChildren = SubscribeRoute._addFileChildren(SubscribeRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CollectionSlugRouteChildren {
  CollectionSlugVariantRoute: typeof CollectionSlugVariantRoute
  CollectionSlugIndexRoute: typeof CollectionSlugIndexRoute
}

const CollectionSlugRouteChildren: CollectionSlugRouteChildren = {
  CollectionSlugVariantRoute: CollectionSlugVariantRoute,
  CollectionSlugIndexRoute: CollectionSlugIndexRoute,
}

const CollectionSlugRouteWithChildren = CollectionSlugRoute._addFileChildren(
  CollectionSlugRouteChildren,
)

interface CollectionRouteChildren {
  CollectionSlugRoute: typeof CollectionSlugRouteWithChildren
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionSlugRoute: CollectionSlugRouteWithChildren,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

interface JournalRouteChildren {
  JournalIndexRoute: typeof JournalIndexRoute
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalIndexRoute: JournalIndexRoute,
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscribeRoute: SubscribeRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtelierRoute: AtelierRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CollectionRoute: CollectionRouteWithChildren,
  ConciergeRoute: ConciergeRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRoute,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  ManifestoRoute: ManifestoRoute,
  MembershipRoute: MembershipRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscriptionRoute: SubscriptionRoute,
  SystemRoute: SystemRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  ApiConciergeImageRoute: ApiConciergeImageRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
